<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Search resultsOver 1,000 places in Bandung</name>
   <tag></tag>
   <elementGuidId>5001d4ab-dbf5-431a-8e62-1fd41800b5c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.hpipapi.dir.dir-ltr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/div/div/div/section/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a0c5e39e-7b44-4852-ba5c-904a9467f6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b4807c63-e6da-438b-9477-8cce5e346406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hpipapi dir dir-ltr</value>
      <webElementGuid>beab2e70-0f65-4666-8414-bdbbf27fe8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elementtiming</name>
      <type>Main</type>
      <value>LCP-target</value>
      <webElementGuid>7f868d17-97c4-41d7-b207-4e7312395933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search resultsOver 1,000 places in Bandung</value>
      <webElementGuid>12315a32-9a80-4981-a97d-0be08d76ebe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;l196t2l1 dir dir-ltr&quot;]/div[@class=&quot;fpnr80 dir dir-ltr&quot;]/div[@class=&quot;c1yo0219 dir dir-ltr&quot;]/div[1]/div[@class=&quot;t17a5psn dir dir-ltr&quot;]/section[1]/h1[@class=&quot;hpipapi dir dir-ltr&quot;]</value>
      <webElementGuid>561aef91-4ada-427d-854f-5eece46be21b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/div/div/div/section/h1</value>
      <webElementGuid>1dbe765e-c421-4e91-a256-6330c5526412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show map'])[1]/following::h1[1]</value>
      <webElementGuid>46a48616-0bca-427a-b38b-d3010b6cd504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/following::h1[1]</value>
      <webElementGuid>eb76969c-bb32-4edb-919b-585dd508fceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>16178f3f-9728-4d8e-805d-538aaa766614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Search resultsOver 1,000 places in Bandung' or . = 'Search resultsOver 1,000 places in Bandung')]</value>
      <webElementGuid>98e22995-b896-471a-8770-97b2a5f57137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
